name: Demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Async Github Branch To Gitee
      uses: shanghaobo/github-branch-gitee@master
      with:
        github_repo: shanghaobo/test-async
        github_branch: master
        gitee_repo: tf-zh/tf-zh.github.io
        gitee_branch: master
        username: ${{ secrets.GITEE_USERNAME }}
        password: ${{ secrets.GITEE_PASSWORD }}
